# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\transposition.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(622, 551)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 100, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(250, 0, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 340, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.plain_text = QtWidgets.QTextEdit(Dialog)
        self.plain_text.setGeometry(QtCore.QRect(160, 90, 331, 81))
        self.plain_text.setObjectName("plain_text")
        self.cipher_text = QtWidgets.QTextEdit(Dialog)
        self.cipher_text.setGeometry(QtCore.QRect(160, 330, 331, 81))
        self.cipher_text.setObjectName("cipher_text")
        self.encrypt_btn = QtWidgets.QPushButton(Dialog)
        self.encrypt_btn.setGeometry(QtCore.QRect(200, 450, 75, 23))
        self.encrypt_btn.setObjectName("encrypt_btn")
        self.decrypt_btn = QtWidgets.QPushButton(Dialog)
        self.decrypt_btn.setGeometry(QtCore.QRect(370, 450, 75, 23))
        self.decrypt_btn.setObjectName("decrypt_btn")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 230, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.key = QtWidgets.QTextEdit(Dialog)
        self.key.setGeometry(QtCore.QRect(160, 210, 331, 81))
        self.key.setObjectName("key")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "encrypt"))
        self.label_2.setText(_translate("Dialog", "Transposition"))
        self.label_3.setText(_translate("Dialog", "decrypt"))
        self.encrypt_btn.setText(_translate("Dialog", "Encrypt"))
        self.decrypt_btn.setText(_translate("Dialog", "Decrypt"))
        self.label_4.setText(_translate("Dialog", "key"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
